# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Async' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TinyConstraints'
  pod 'Reveal-SDK'
  pod 'AWSMobileClient'
  pod 'AWSPinpoint'

  # Pods for Async

  target 'AsyncTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AsyncUITests' do
    # Pods for testing
  end

end
